// Generated by CodiumAI

import { render, screen } from '@testing-library/react'
import { Gallery } from '~/infrastructure/ui/components/Gallery'
// Generated by CodiumAI

describe('code snippet', () => {
  // Tests that the gallery title is displayed with correct data-testid
  it('should display gallery title with correct data-testid', () => {
    const { getByTestId } = render(<Gallery title="Test Gallery" images={[]} />)
    const galleryTitle = getByTestId('gallery-Test Gallery')
    expect(galleryTitle).toBeInTheDocument()
  })

  // Tests that images are displayed with correct data-testid
  it('should display images with correct data-testid', () => {
    const images = ['https://example.com/image1.jpg', '/image2.jpg']
    const { getAllByTestId } = render(
      <Gallery title="Test Gallery" images={images} />
    )
    const imageElements = getAllByTestId(/image-Test Gallery-index/)
    expect(imageElements.length).toBe(images.length)
  })

  // Tests that the gallery has correct flexbox layout
  it('should have correct flexbox layout', () => {
    const { container } = render(<Gallery title="Test Gallery" images={[]} />)
    expect(container.firstChild).toHaveClass(
      'flex',
      'flex-col',
      'w-full',
      'gap-4'
    )
  })

  // Tests that images are rendered with correct alt text and dimensions
  it('should render images with correct alt text and dimensions', () => {
    const images = ['https://example.com/image1.jpg', '/image2.jpg']
    const { getAllByAltText } = render(
      <Gallery title="Test Gallery" images={images} />
    )
    const imageElements = getAllByAltText(/Test Gallery-image/)
    expect(imageElements.length).toBe(images.length)
    imageElements.forEach((image) => {
      expect(image).toHaveAttribute('width', '200')
      expect(image).toHaveAttribute('height', '200')
    })
  })
})
